# Generated by Django 3.2.12 on 2022-02-26 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_userprofile_subscription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
