# Generated by Django 3.2.12 on 2022-02-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_alter_userprofile_subscription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_city',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_district',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_neighborhood',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
