# Generated by Django 3.2.12 on 2022-02-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0007_userfeeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=255)),
                ('platform_short_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
