# Generated by Django 3.2.12 on 2022-02-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0008_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeeditem',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users_api.platform'),
            preserve_default=False,
        ),
    ]
